# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion/bin/cmake/bin/cmake

# The command to remove a file.
RM = /opt/clion/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ilya/code/jetshow

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ilya/code/jetshow

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ilya/code/jetshow/CMakeFiles /home/ilya/code/jetshow/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ilya/code/jetshow/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jetshow

# Build rule for target.
jetshow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jetshow
.PHONY : jetshow

# fast build rule for target.
jetshow/fast:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/build
.PHONY : jetshow/fast

src/bfields.o: src/bfields.cpp.o

.PHONY : src/bfields.o

# target to build an object file
src/bfields.cpp.o:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/bfields.cpp.o
.PHONY : src/bfields.cpp.o

src/bfields.i: src/bfields.cpp.i

.PHONY : src/bfields.i

# target to preprocess a source file
src/bfields.cpp.i:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/bfields.cpp.i
.PHONY : src/bfields.cpp.i

src/bfields.s: src/bfields.cpp.s

.PHONY : src/bfields.s

# target to generate assembly for a file
src/bfields.cpp.s:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/bfields.cpp.s
.PHONY : src/bfields.cpp.s

src/geometry.o: src/geometry.cpp.o

.PHONY : src/geometry.o

# target to build an object file
src/geometry.cpp.o:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/geometry.cpp.o
.PHONY : src/geometry.cpp.o

src/geometry.i: src/geometry.cpp.i

.PHONY : src/geometry.i

# target to preprocess a source file
src/geometry.cpp.i:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/geometry.cpp.i
.PHONY : src/geometry.cpp.i

src/geometry.s: src/geometry.cpp.s

.PHONY : src/geometry.s

# target to generate assembly for a file
src/geometry.cpp.s:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/geometry.cpp.s
.PHONY : src/geometry.cpp.s

src/jet.o: src/jet.cpp.o

.PHONY : src/jet.o

# target to build an object file
src/jet.cpp.o:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/jet.cpp.o
.PHONY : src/jet.cpp.o

src/jet.i: src/jet.cpp.i

.PHONY : src/jet.i

# target to preprocess a source file
src/jet.cpp.i:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/jet.cpp.i
.PHONY : src/jet.cpp.i

src/jet.s: src/jet.cpp.s

.PHONY : src/jet.s

# target to generate assembly for a file
src/jet.cpp.s:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/jet.cpp.s
.PHONY : src/jet.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/nfields.o: src/nfields.cpp.o

.PHONY : src/nfields.o

# target to build an object file
src/nfields.cpp.o:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/nfields.cpp.o
.PHONY : src/nfields.cpp.o

src/nfields.i: src/nfields.cpp.i

.PHONY : src/nfields.i

# target to preprocess a source file
src/nfields.cpp.i:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/nfields.cpp.i
.PHONY : src/nfields.cpp.i

src/nfields.s: src/nfields.cpp.s

.PHONY : src/nfields.s

# target to generate assembly for a file
src/nfields.cpp.s:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/nfields.cpp.s
.PHONY : src/nfields.cpp.s

src/vfields.o: src/vfields.cpp.o

.PHONY : src/vfields.o

# target to build an object file
src/vfields.cpp.o:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/vfields.cpp.o
.PHONY : src/vfields.cpp.o

src/vfields.i: src/vfields.cpp.i

.PHONY : src/vfields.i

# target to preprocess a source file
src/vfields.cpp.i:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/vfields.cpp.i
.PHONY : src/vfields.cpp.i

src/vfields.s: src/vfields.cpp.s

.PHONY : src/vfields.s

# target to generate assembly for a file
src/vfields.cpp.s:
	$(MAKE) -f CMakeFiles/jetshow.dir/build.make CMakeFiles/jetshow.dir/src/vfields.cpp.s
.PHONY : src/vfields.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... jetshow"
	@echo "... src/bfields.o"
	@echo "... src/bfields.i"
	@echo "... src/bfields.s"
	@echo "... src/geometry.o"
	@echo "... src/geometry.i"
	@echo "... src/geometry.s"
	@echo "... src/jet.o"
	@echo "... src/jet.i"
	@echo "... src/jet.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/nfields.o"
	@echo "... src/nfields.i"
	@echo "... src/nfields.s"
	@echo "... src/vfields.o"
	@echo "... src/vfields.i"
	@echo "... src/vfields.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

